"""
Utility functions for ShEPhERD inference scaling.

This module provides helper functions for working with ShEPhERD's inference output.
"""

import logging
from copy import deepcopy
import numpy as np

from rdkit import Chem
from rdkit.Chem import rdDetermineBonds


def get_xyz_content(sample):
    """
    Generate XYZ file content string from a ShEPhERD sample.
    
    Args:
        sample (dict): ShEPhERD output dictionary with x1 containing atoms and positions.
        
    Returns:
        str: XYZ file content or None if input is invalid.
    """
    if 'x1' not in sample or 'atoms' not in sample['x1'] or 'positions' not in sample['x1']:
        logging.warning("Invalid sample format for XYZ generation")
        return None

    try:
        atoms = sample['x1']['atoms']
        positions = sample['x1']['positions']

        xyz_lines = [f"{len(atoms)}", "Generated by ShEPhERD Inference"]
        for i in range(len(atoms)):
            try:
                atomic_number = int(atoms[i])
                # attempt to get symbol, default to element number if fails
                try:
                    symbol = Chem.Atom(atomic_number).GetSymbol()
                except Exception:
                    symbol = str(atomic_number)
                pos = positions[i]
                xyz_lines.append(f"{symbol} {pos[0]:>15.8f} {pos[1]:>15.8f} {pos[2]:>15.8f}")
            except (ValueError, IndexError) as e:
                logging.warning(f"Skipping atom {i} due to data issue: {e}")
                continue

        xyz_lines[0] = str(len(xyz_lines) - 2)

        return "\n".join(xyz_lines)

    except Exception as e:
        logging.error(f"Error generating XYZ content: {e}")
        return None


def create_rdkit_molecule(sample):
    """
    Create an RDKit molecule from ShEPhERD output using XYZ block approach.
    
    Args:
        sample (dict): ShEPhERD output dictionary with x1 containing atoms and positions.
        
    Returns:
        rdkit.Chem.rdchem.Mol: RDKit molecule object or None if conversion fails.
    """
    if 'x1' not in sample:
        logging.warning("No atom data (x1) found in sample")
        return None

    try:
        # extract atoms and their positions from x1
        atoms = sample['x1']['atoms']
        positions = sample['x1']['positions']

        # create XYZ format string
        xyz = f'{len(atoms)}\n\n'
        for a in range(len(atoms)):
            atomic_number = int(atoms[a])
            position = positions[a]
            symbol = Chem.Atom(atomic_number).GetSymbol()
            xyz += f'{symbol} {position[0]:.3f} {position[1]:.3f} {position[2]:.3f}\n'

        # create molecule from XYZ block
        mol = Chem.MolFromXYZBlock(xyz)
        if mol is None:
            logging.warning("Failed to create molecule from XYZ block")
            return None

        # try different charge states for bond determination
        mol_final = None
        for charge in [0, 1, -1, 2, -2]:
            mol_copy = deepcopy(mol)
            try:
                rdDetermineBonds.DetermineBonds(mol_copy, charge=charge, embedChiral=True)
                logging.debug(f"Bond determination successful with charge {charge}")
                mol_final = mol_copy
                break
            except Exception as e:
                logging.debug(f"Bond determination failed with charge {charge}: {e}")
                continue

        if mol_final is None:
            logging.warning("Bond determination failed for all charge states")
            return None
        
        # validate molecule
        try:
            radical_electrons = sum([a.GetNumRadicalElectrons() for a in mol_final.GetAtoms()])
            if radical_electrons > 0:
                logging.warning(f"Molecule has {radical_electrons} radical electrons")
            
            mol_final.UpdatePropertyCache()
            Chem.GetSymmSSSR(mol_final)
            logging.debug("Molecule validation successful")
        except Exception as e:
            logging.warning(f"Molecule validation failed: {e}")
            return None

        # try to generate SMILES to verify molecule
        try:
            smiles = Chem.MolToSmiles(mol_final)
            logging.debug(f"Generated SMILES: {smiles}")
        except Exception as e:
            logging.warning(f"SMILES generation failed: {e}")

        if '.' in smiles:
            logging.warning("Molecule is a fragment, failed to create molecule")
            return None

        return mol_final
        
    except Exception as e:
        logging.warning(f"Error creating molecule: {e}")
        return None
    

def remove_overlaps(generated_sample: dict,
                    inpainted_atom_positions: np.ndarray,
                    cutoff: float = 0.7,
                    verbose: bool = False) -> dict:
    """
    Remove atoms that overlap with inpainted atoms.
    Assumes `inpainted_atom_positions` are the first `num_inpainted_atoms` atoms in `generated_sample['x1']['positions']`.

    Args:
        generated_sample (dict): ShEPhERD output dictionary with x1 containing atoms and positions.
        inpainted_atom_positions (np.ndarray) : Array of inpainted atom positions. (num_inpainted_atoms, 3)
        cutoff (float): Cutoff distance (RMSD) for overlap. (default: 0.7)
        verbose (bool): Whether to print verbose output. (default: False)

    Returns:
        deepcopy(generated_sample):
        ShEPhERD output dictionary where atoms that overlap with inpainted atoms are removed.
        Note that this does not alter the bond information.
    """
    num_total_atoms = len(generated_sample['x1']['positions'])
    num_inpainted_atoms = len(inpainted_atom_positions)
    diffused_atom_pos = generated_sample['x1']['positions'][num_inpainted_atoms:]
    pairwise_diff = diffused_atom_pos[:, None] - inpainted_atom_positions[None, :]
    rmse_atoms = np.sqrt(np.mean(np.square(pairwise_diff), axis=2))
    overlap_inds = np.where(np.any(np.isclose(rmse_atoms, np.zeros(rmse_atoms.shape), atol=cutoff), axis=1))[0]
    if verbose:
        print(f'Removing inds: {overlap_inds + num_inpainted_atoms}')
    inds_to_keep = np.array([i for i in range(num_total_atoms) if i not in overlap_inds + num_inpainted_atoms])
    out = deepcopy(generated_sample)
    out['x1']['positions'] = generated_sample['x1']['positions'][inds_to_keep]
    out['x1']['atoms'] = generated_sample['x1']['atoms'][inds_to_keep]
    return out


def remove_side_groups_with_geometry(mol: Chem.Mol, atoms_to_remove: list[int]) -> Chem.Mol:
    """
    Remove atoms in `atoms_to_remove` and add hydrogens using RDKit's AddHs(addCoords=True)
    to preserve 3D geometry. Returns a new RDKit molecule.
    
    Args:
        mol: RDKit molecule with conformer
        atoms_to_remove: list of atom indices to delete

    Returns:
        RDKit molecule with hydrogens added and side groups removed.
    """
    conf = mol.GetConformer()
    pos = conf.GetPositions()
    
    atoms_to_keep = sorted(set(range(mol.GetNumAtoms())) - set(atoms_to_remove))
    
    old_to_new = {old_idx: new_idx for new_idx, old_idx in enumerate(atoms_to_keep)}

    rw_mol = Chem.RWMol() # editable mol
    atom_map = {}

    for idx in atoms_to_keep:
        atom = mol.GetAtomWithIdx(idx)
        new_atom = Chem.Atom(atom.GetAtomicNum())
        new_idx = rw_mol.AddAtom(new_atom)
        atom_map[idx] = new_idx

    for bond in mol.GetBonds():
        a1, a2 = bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
        if a1 in atoms_to_keep and a2 in atoms_to_keep:
            rw_mol.AddBond(atom_map[a1], atom_map[a2], bond.GetBondType())

    new_mol = rw_mol.GetMol()
    new_conf = Chem.Conformer(len(atoms_to_keep))

    for new_idx, old_idx in enumerate(atoms_to_keep):
        x, y, z = pos[old_idx]
        new_conf.SetAtomPosition(new_idx, (x, y, z))

    new_mol.RemoveAllConformers()
    new_mol.AddConformer(new_conf, assignId=True)

    Chem.SanitizeMol(new_mol)
    mol_with_H = Chem.AddHs(new_mol, addCoords=True)

    return mol_with_H
