name: shepherd
channels:
  - pytorch
  - pyg
  - merv
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.5.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - chardet=5.2.0
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - contourpy=1.1.1
  # - cudatoolkit=11.3.1
  - cycler=0.12.1
  - dftd4=3.6.0
  - envvar-pythonnousersite-true=0.1.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gnutls=3.7.9
  - greenlet=3.0.3
  - h2=4.1.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2021.4.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - markupsafe=2.1.5
  - matplotlib-base=3.7.3
  - mctc-lib=0.3.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.9.1
  - numpy=1.24.4
  - olefile=0.47
  - openh264=2.3.1
  - openssl=3.4.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.0.3
  - pcre2=10.43
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pycairo=1.25.0
  - pycparser=2.22
  - pyg=2.2.0
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.8.13
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.16
  - pytz=2024.2
  - rdkit=2023.03.3
  - readline=8.2
  - reportlab=3.5.68
  - requests=2.32.3
  - rlpycairo=0.2.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - simple-dftd3=1.0.0
  - six=1.16.0
  - sqlalchemy=1.3.24
  - sqlite=3.39.2
  - svt-av1=1.4.1
  - tblite=0.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml-f=0.4.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xtb=6.6.1
  - xz=5.2.6
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - click==8.1.7
      - comm==0.2.2
      - configargparse==1.7
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - e3nn==0.5.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - flask==3.0.3
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.66.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - importlib-metadata==8.4.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - lightning-utilities==0.11.6
      - markdown==3.7
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==24.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.23.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeprecate==0.3.2
      - pygments==2.18.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==1.6.3
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - rsa==4.9
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - setproctitle==1.3.4
      - setuptools==59.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.2
      - tenacity==9.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch-ema==0.3
      - torchmetrics==1.4.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240821
      - uri-template==1.3.0
      - wandb==0.19.6
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - yarl==1.9.4
